
### lib path
LIB_PATH = ${PROJECT_PATH}/..


### thread lock lib
PATH_THREAD_LOCK = $(LIB_PATH)/threadLockLib
INC_THREAD_LOCK  = -I$(PATH_THREAD_LOCK)/include
LIB_THREAD_LOCK  = -L$(PATH_THREAD_LOCK)/lib -llibthreadLock.a

